/**
 * Subjects - Who or what is acting? (100+ entries)
 * Used in history seeds: [Subject] [Action] [Object]
 */
export const SUBJECTS = [
	// Organizations & Groups
	'An ancient order',
	'A forgotten empire',
	'The last survivors',
	'A wandering tribe',
	'An underground cult',
	'A merchant guild',
	'The royal court',
	'A band of outcasts',
	'The scholarly order',
	'A rival faction',
	'The common folk',
	'A secret society',
	'The ruling elite',
	'The military council',
	'A religious sect',
	'The old nobility',
	'A rebel alliance',
	'The artisan guilds',
	'A mercenary company',
	'The border clans',
	'An exiled house',
	'The temple priests',
	'A trading consortium',
	'The criminal underworld',
	'A monastic order',
	'The coastal settlements',
	'An indigenous nation',
	'The colonizers',
	'A resistance movement',
	'The bureaucracy',
	'An academy of scholars',
	'The nomadic peoples',
	'A diplomatic envoy',
	'The frontier settlers',
	'An enslaved population',
	'The revolutionaries',
	'A clandestine network',
	'The landed gentry',
	'An ancient bloodline',
	'The council of elders',
	
	// Individuals & Archetypes
	'A prophet',
	'An inventor',
	'A conqueror',
	'A peacemaker',
	'A betrayer',
	'The chosen one',
	'A foreign envoy',
	'The old guard',
	'Young rebels',
	'A mysterious stranger',
	'The fallen hero',
	'A desperate leader',
	'The lost heir',
	'A wise advisor',
	'A vengeful spirit',
	'A legendary beast',
	'The untouchables',
	'A mad visionary',
	'The sworn protector',
	'A ruthless general',
	'The last witness',
	'A reformed villain',
	'The silent observer',
	'A charismatic speaker',
	'The hidden mastermind',
	'A reluctant champion',
	'The eternal wanderer',
	'A zealous believer',
	'The voice of reason',
	'A cunning diplomat',
	'The broken warrior',
	'A mysterious healer',
	'The keeper of secrets',
	'A rogue scholar',
	'The last of their kind',
	'A young prodigy',
	'The disgraced noble',
	'A returning exile',
	'The true believer',
	'A scheming courtier',
	
	// Abstract/Conceptual
	'The forces of change',
	'An old curse',
	'The weight of tradition',
	'A new ideology',
	'The tide of progress',
	'An ancient prophecy',
	'The spirit of rebellion',
	'A dark conspiracy',
	'The light of hope',
	'An unstoppable force',
	'The hand of fate',
	'A forgotten truth',
	'The shadow of war',
	'An emerging power',
	'The dying embers',
	'A rising generation',
	'The bitter past',
	'An uncertain future',
	'The cycle of revenge',
	'A moment of crisis'
];

/**
 * Actions - What is being done? (100+ entries)
 * Used in history seeds: [Subject] [Action] [Object]
 */
export const ACTIONS = [
	// Creation & Destruction
	'discovers',
	'destroys',
	'creates',
	'abandons',
	'transforms',
	'rebuilds',
	'shatters',
	'forges',
	'unmakes',
	'constructs',
	'demolishes',
	'establishes',
	'dismantles',
	'resurrects',
	'buries',
	'raises',
	'razes',
	'births',
	'ends',
	'renews',
	
	// Social & Political
	'challenges',
	'unites',
	'divides',
	'corrupts',
	'purifies',
	'betrays',
	'liberates',
	'enslaves',
	'crowns',
	'deposes',
	'allies with',
	'wages war on',
	'negotiates with',
	'dominates',
	'serves',
	'opposes',
	'manipulates',
	'inspires',
	'terrorizes',
	'civilizes',
	
	// Knowledge & Truth
	'reveals',
	'conceals',
	'questions',
	'answers',
	'remembers',
	'forgets',
	'teaches',
	'learns from',
	'investigates',
	'proves',
	'disproves',
	'prophesies',
	'decodes',
	'encrypts',
	'interprets',
	'misunderstands',
	'illuminates',
	'obscures',
	'witnesses',
	'documents',
	
	// Change & Movement
	'awakens',
	'silences',
	'embraces',
	'flees from',
	'confronts',
	'evades',
	'pursues',
	'returns to',
	'departs from',
	'crosses',
	'bridges',
	'severs',
	'connects',
	'isolates',
	'gathers',
	'scatters',
	'ascends to',
	'falls from',
	'transcends',
	'regresses to',
	
	// Value & Exchange
	'sacrifices',
	'preserves',
	'celebrates',
	'mourns',
	'honors',
	'desecrates',
	'steals',
	'gifts',
	'hoards',
	'shares',
	'exploits',
	'protects',
	'trades',
	'sells out',
	'ransoms',
	'redeems',
	'invests in',
	'squanders',
	'inherits',
	'bequeaths'
];

/**
 * Objects - What is affected? (100+ entries)
 * Used in history seeds: [Subject] [Action] [Object]
 */
export const OBJECTS = [
	// Physical Items & Places
	'an ancient artifact',
	'a sacred temple',
	'the forbidden archives',
	'a hidden fortress',
	'the great city',
	'a precious resource',
	'the ancestral lands',
	'a powerful weapon',
	'the royal treasury',
	'a mysterious ruin',
	'the border territories',
	'a legendary tomb',
	'the merchant routes',
	'a natural wonder',
	'the capital itself',
	'a secret passage',
	'the harvest lands',
	'a divine relic',
	'the prison complex',
	'a strategic position',
	
	// Abstract Concepts
	'the forbidden knowledge',
	'a powerful alliance',
	'the old ways',
	'a new belief',
	'a terrible secret',
	'the source of power',
	'an impossible choice',
	'a forgotten promise',
	'the laws of nature',
	'the bonds of family',
	'a dangerous truth',
	'the price of peace',
	'an unexpected connection',
	'the weight of history',
	'a symbol of hope',
	'the edge of extinction',
	'a lasting legacy',
	'the cycle of violence',
	'a bridge to the past',
	'the seeds of change',
	
	// Social Structures
	'a fragile treaty',
	'the essence of humanity',
	'the spirit of rebellion',
	'a divine mandate',
	'the cost of progress',
	'a sacred tradition',
	'the boundary between worlds',
	'a technological marvel',
	'the natural order',
	'a cultural identity',
	'the chain of command',
	'a social contract',
	'the balance of power',
	'a moral standard',
	'the rule of law',
	'a revolutionary ideal',
	'the class hierarchy',
	'a common language',
	'the bonds of kinship',
	'a shared history',
	
	// Relationships & Bonds
	'an ancient rivalry',
	'a forbidden love',
	'the trust of allies',
	'a blood oath',
	'the loyalty of followers',
	'a sworn enemy',
	'the respect of peers',
	'a mentor relationship',
	'the faith of believers',
	'a marriage alliance',
	'the bond of siblings',
	'a generational feud',
	'the oath of office',
	'a diplomatic immunity',
	'the honor of family',
	'a business partnership',
	'the ties that bind',
	'a reluctant alliance',
	'the chains of obligation',
	'a debt of gratitude',
	
	// Time & Change
	'the turning point',
	'a moment of truth',
	'the end of an era',
	'a new beginning',
	'the final chapter',
	'a crossroads',
	'the point of no return',
	'a window of opportunity',
	'the calm before storm',
	'a critical juncture'
];

/**
 * Circumstances - When/How? (100+ entries)
 * Used to add context: [Seed] [Circumstance]
 */
export const CIRCUMSTANCES = [
	// Timing
	'during a time of crisis',
	'at the height of prosperity',
	'in the aftermath of war',
	'on the eve of a great change',
	'while hidden forces stir',
	'as old powers awaken',
	'when all seems lost',
	'during a golden age',
	'in a moment of doubt',
	'while the world watches',
	'for the first time',
	'for the last time',
	'too late',
	'before its time',
	'at the worst possible moment',
	'just in time',
	'after years of waiting',
	'in the dead of night',
	'at high noon',
	'during the harvest season',
	
	// Manner
	'in secret',
	'against all odds',
	'under a dark omen',
	'by accident',
	'through sacrifice',
	'with unexpected allies',
	'through treachery',
	'with great ceremony',
	'in defiance of tradition',
	'according to prophecy',
	'despite fierce opposition',
	'with borrowed power',
	'through cunning alone',
	'by ancient right',
	'through sheer will',
	'with divine blessing',
	'under false pretenses',
	'by popular demand',
	'through bloody conquest',
	'with peaceful intent',
	
	// Context
	'as empires crumble',
	'while plague spreads',
	'as resources dwindle',
	'while borders shift',
	'as beliefs change',
	'while others sleep',
	'as the old guard fades',
	'while new powers rise',
	'as chaos spreads',
	'while order breaks down',
	'as the climate shifts',
	'while technology advances',
	'as magic awakens',
	'while gods intervene',
	'as prophecies unfold',
	'while destinies intertwine',
	'as alliances crumble',
	'while trust erodes',
	'as hope returns',
	'while darkness gathers',
	
	// Stakes
	'with everything at stake',
	'with nothing to lose',
	'risking total destruction',
	'for a chance at redemption',
	'to prevent catastrophe',
	'to fulfill a promise',
	'to right an ancient wrong',
	'to claim what was lost',
	'to prove a point',
	'to save what matters most',
	'to escape the past',
	'to shape the future',
	'to preserve a legacy',
	'to end a cycle',
	'to begin anew',
	'to honor the fallen',
	'to avenge the wronged',
	'to break free',
	'to find meaning',
	'to discover the truth'
];
